server:
  port: 8888

spring:
  application:
    name: driving-system
  datasource:
    url: jdbc:mysql://localhost:3306/driving_system?characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 12345678
